DROP TABLE MEDICAMENTOS IF EXISTS;
CREATE TABLE MEDICAMENTOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
LABORATORIO VARCHAR(50) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO DECIMAL(7,2) NOT NULL
);
INSERT INTO MEDICAMENTOS VALUES (DEFAULT, 'IBUPIRAC', 'BAYER', 10, 50),
(DEFAULT, 'ACTRON', 'BAYER', 15, 65), (DEFAULT, 'ASPIRINA', 'BAYER', 5, 20);